<section class="login">
    <?php
    $this->headScript()
            ->appendFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
            ->appendFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.pack.js')
            ->appendFile($this->basePath() . '/js/fancybox/source/helpers/jquery.fancybox-buttons.js');
    $this->headLink()
            ->appendStylesheet($this->basePath() . '/css/dropzone.css')
            ->appendStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/south-street/jquery-ui.css')
            ->appendStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox.css')
            ->appendStylesheet($this->basePath() . '/css/fancybox/helpers/jquery.fancybox-buttons.css');
    ?>
    <script>
        Dropzone.autoDiscover = false;
        $(document).ready(function () {
            $(".fancybox-button").fancybox({
                prevEffect: 'none',
                nextEffect: 'none',
                closeBtn: false,
                helpers: {
                    title: {type: 'inside'},
                    buttons: {}
                }
            });
            var myDropzone = new Dropzone("form#dropit",{
                url: "<?= $this->url('users/editprofile/sub', array('action' => 'uploadwork')); ?>",
                //maxFilesize: 2, // MB
                maxFiles: 100,
                autoProcessQueue: false,
                previewsContainer: '.dropzone-previews',
                uploadMultiple: true,
                parallelUploads: 100,
                addRemoveLinks: true,
                dictDefaultMessage: 'Drop Images (or click) here to Upload',
                init: function () {
                    this.on("processing", function (file) {
                        this.options.autoProcessQueue = true;
                    });
                    this.on("queuecomplete", function (file) {
                        this.options.autoProcessQueue = false;
                    });

                    this.on("successmultiple", function (files, response) {
                        //alert(JSON.stringify(response));
                        /*jQuery.each(files, function(index, value) {
                            jQuery.each(value, function(inde, valu) {
                            alert(inde+' : '+valu); 
                            });    
                        });*/
                        if(response.done == 'ok'){
                            $.notify("Work Project Saved Successfully.", {position:"top-left",className: 'success'});
                            this.removeAllFiles();
                        }else{
                            alert('Invalid Data');
                        }
                        $(file.previewTemplate).append('<span style="display:none;" class="server_file">' + response + '</span>');
                    });
                    
                    this.on("removedfile", function (file) {
                        
                        var server_file = $(file.previewTemplate).children('.server_file').text();
                        // Do a post request and pass this path and use server-side language to delete the file
                        $.post("delete.php", {file_to_be_deleted: server_file});
                    });
                }
            });
            $('#add_img').click(function (e) {
                e.preventDefault();
                myDropzone.processQueue();
            });
            
            $('#edit_info').click(function (e) {
                e.preventDefault();
                $.ajax({
                    url: '<?= $this->url('users/editprofile/sub', array('action' => 'processedit')); ?>',
                    type: 'post',
                    data: $('#Profile').serialize(),
                    success: function(data){
                        if(data.done == 'ok'){
                            $.notify("Personal Info Successfully Updated.", {position:"top-left",className: 'success'});
                        }else{
                            $.notify("Personal Info Update Unsuccessful.", {position:"top-left",className: 'error'});
                        }
                    }
                });
            });
        });
    </script>
    <h2>Profile Edit</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as
            indicated below.
        </p>
    <?php endif; ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Login', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $user = $form->get('user');
    $work = $form->get('work');
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($user->get('fullName')); ?></dt>
        <dd><?php
    echo $this->formElement($user->get('fullName'));
    echo $this->formElementErrors($user->get('fullName'));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('country'));
    ?></dt>
        <dd><?php
        echo $this->formElement($user->get('country'));
        echo $this->formElementErrors($user->get('country'));
    ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit')->setValue('Edit'));
            echo $this->formElementErrors($form->get('submit'));
    ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
    <h3>Add Previous Work</h3>

    <form class="dropzone" id="dropit">
        <div class="dropzone-previews"></div>
        <input name="work[id]" type="hidden" value="0">
        <input name="work[subject]" type="text" placeholder="Enter subject Here"><br><br>
        <textarea style="width:250px;height:135px;" name="work[description]" placeholder="Enter description here"></textarea><br><br>
        <input name="work[url]" type="text" placeholder="Enter a link"><br><br>
        <button id="add_img">Add</button><br><br>
    </form>
    <? if (!empty($this->work)) : ?>
        <?php foreach ($this->work as $index => $array): ?>
            <h3><?= $array['subject']; ?></h3>
            <div class="ocarousel_slider">  
                <div class="ocarousel example_photos" data-ocarousel-perscroll="3">
                    <div class="ocarousel_window">
                        <a class="fancybox-button img-responsive" rel="gallery<?= $array['id']; ?>" href="image/Portfolio.png" title="<?= $array['description']; ?>">
                            <img style="width:340px;height:224;" src="image/Portfolio.png" alt="">
                        </a>
                        <?php foreach ($array['img'] as $img): ?>
                            <a class="fancybox-button img-responsive" rel="gallery<?= $array['id']; ?>" href="<?= "image/$img"; ?>" title="">
                                <img style="width:340px;height:224;" src="<?= "image/$img"; ?>" alt="" />
                            </a>
                        <?php endforeach; ?>
                    </div>
                    <span>           
                        <a href="#" data-ocarousel-link="left" class="prev"><i class="fa fa-angle-left"></i> </a>
                        <a href="#" data-ocarousel-link="right" class="next"> <i class="fa fa-angle-right"></i></a>
                    </span>
                </div>
            </div> 
        <?php endforeach; ?>

    <? endif; ?>
</section>
