<section class="login">
    <h2>Login</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as
            indicated below.
        </p>
    <?php endif; ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Login', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $user = $form->get('user');
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($user->get('fullName')); ?></dt>
        <dd><?php
    echo $this->formElement($user->get('fullName'));
    echo $this->formElementErrors($user->get('fullName'));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('country'));
    ?></dt>
        <dd><?php
        echo $this->formElement($user->get('country'));
        echo $this->formElementErrors($user->get('country'));
    ?></dd>
        <h3>Add Previous Work</h3>
        <dd><?php
            echo $this->formCollection($form->get('work'));
            echo $this->formElement($form->get('submit')->setValue('Edit'));
            echo $this->formElementErrors($form->get('submit'));
    ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>