<section class="user-manager">
    <h2>Users</h2>
    <table width="100%">
        <thead>
        <th width="20%">Name</th>
        <th width="40%">Email</th>
        <th></th>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <tr>    
                    <td><?= $user->name; ?></td>
                    <td><?= $user->email; ?></td>
                    <td><a href="<?= $this->url('users/user-manager', array('action' => 'edit', 'id' => $user->id)); ?>">Edit </a>|<a href="<?= $this->url('users/user-manager', array('action' => 'delete', 'id' => $user->id)); ?>"> Delete</a></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="3"><a href="<?= $this->url('users/user-manager', array('action' => 'add')); ?>">Add User</a></td>
            </tr>
        </tbody>
    </table>
</section>