<section class="register">
    <h2>Register</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as
            indicated below.
        </p>
    <?php endif; ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Register', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $user = $form->get('user');
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($user->get('fullName')); ?></dt>
        <dd><?php
    echo $this->formElement($user->get('fullName'));
    echo $this->translate($this->formElementErrors($user->get('fullName')));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('email')); ?></dt>
        <dd><?php
            echo $this->formElement($user->get('email'));
            echo $this->translate($this->formElementErrors($user->get('email')));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('phone')); ?></dt>
        <dd><?php
            echo $this->formElement($user->get('phone'));
            echo $this->translate($this->formElementErrors($user->get('phone')));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('country')); ?></dt>
        <dd><?php
            echo $this->formElement($user->get('country'));
            echo $this->translate($this->formElementErrors($user->get('country')));
    ?></dd>
        <dt><?php echo $this->formLabel($user->get('password'));
    ?></dt>
        <dd><?php
        echo $this->formElement($user->get('password'));
        echo $this->formElementErrors($user->get('password'));
    ?></dd>
        <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
    ?></dd>
        <dt><?php echo $this->formLabel($form->get('captcha')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('captcha'));
            echo $this->formElementErrors($form->get('captcha'));
    ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
    ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>