<section class="upload-manager">
    <h2>User Uploads</h2>
    <table width="100%">
        <thead>
        <th width="60%">Image</th>
        <th>Actions</th>
        </thead>
        <tbody>
            <?php foreach ($myUploads as $upload): ?>
                <tr>    
                    <td><img src="<?= $this->url('users/media', array('action' => 'showimage', 'id' => $upload->id, 'subaction' => 'thumb')); ?>"><a href="<?= $this->url('users/media', array('action' => 'view', 'id' => $upload->id)); ?>"><?= $upload->label; ?></a></td>
                    <td><a href="<?= $this->url('users/media', array('action' => 'delete', 'id' => $upload->id)); ?>">Delete</a></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="3"><a href="<?= $this->url('users/media', array('action' => 'upload')); ?>">Add Image</a></td>
            </tr>
        </tbody>
    </table>
</section>